- name: Install latest basic editors and packages
  ansible.builtin.dnf:
    name:
      - vim
      - git
      - dnf-automatic
      - nano
    state: latest

- name: Ensure dnf-automatic is running/enabled
  ansible.builtin.service:
    name: dnf-automatic-install.timer
    state: started
    enabled: true