---

- name: import repairPackageManagers.yaml
  import_tasks: repairPackageManagers.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import sudo task
  import_tasks: sudo.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import users task
  import_tasks: users.yaml
  
- name: Import cron task
  import_tasks: cron.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import SUID/SGID task
  import_tasks: suid_sgid.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import auditd task
  import_tasks: auditd.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import login_defs task
  import_tasks: login_defs.yaml
  when: rotatePubkey == false

- name: Import sshd task
  import_tasks: sshd.yaml
  when: rotatePubkey == false

- name: Import UFW task
  import_tasks: ufw.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import Apache task
  import_tasks: apache.yaml
  when: rotatePubkey == false
  ignore_errors: true

- name: Import PHP task
  import_tasks: php.yaml
  when: rotatePubkey == false
  ignore_errors: true
